# Data Acquisition in Python

---

### Essential Libraries

Let us begin by importing the essential Python Libraries.

> NumPy : Library for Numeric Computations in Python  
> Pandas : Library for Data Acquisition and Preparation

In [32]:
# Basic Libraries
import numpy as np
import pandas as pd

---

### Pandas Dataframe

The `pandas` library in Python offers an amazing data structure for data science -- the `DataFrame`.    
It is pretty close to a `dictionary`, and we will start by creating a `DataFrame` from `dictionary`.

In [47]:
canteens_dict = {"Name" : ["North Spine", "Koufu", "Canteen 9", "North Hill", "Canteen 11"],
                 "Stalls" : [20, 15, 10, 12, 8],
                 "Rating" : [4.5, 4.2, 4.0, 3.7, 4.2]
                }

canteens_df = pd.DataFrame(canteens_dict)
canteens_df

          Name  Stalls  Rating
0  North Spine      20     4.5
1        Koufu      15     4.2
2    Canteen 9      10     4.0
3   North Hill      12     3.7
4   Canteen 11       8     4.2

It is super simple to access the columns of the `DataFrame` -- directly use the column names.

In [34]:
canteens_df["Name"]

0    North Spine
1          Koufu
2      Canteen 9
3     North Hill
4     Canteen 11
Name: Name, dtype: object

You may also extract a single record or row from a `DataFrame` -- use `iloc` with the index.

In [35]:
canteens_df.iloc[0]

Name      North Spine
Stalls             20
Rating            4.5
Name: 0, dtype: object

Thus, a Pandas `DataFrame` is really like a table, with structured data accessible in two ways.

---

### Import CSV file into a DataFrame

If the dataset is in a standard CSV format (flat file), we may use the `read_csv` function from Pandas.

In [36]:
csv_data = pd.read_csv('data/somedata.csv', header = None)
csv_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,12.6,12.3,1.0708,23,154.25,67.75,23.7,134.9,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,2,6.9,6.1,1.0853,22,173.25,72.25,23.4,161.3,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,3,24.6,25.3,1.0414,22,154.00,66.25,24.7,116.0,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,4,10.9,10.4,1.0751,26,184.75,72.25,24.9,164.7,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,5,27.8,28.7,1.0340,24,184.25,71.25,25.6,133.1,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7

In [52]:
print("Data type : ", type(csv_data))
print("Data dims : ", csv_data.shape)

Data type :  <class 'pandas.core.frame.DataFrame'>
Data dims :  (252, 19)

---

### Import TXT file into a DataFrame

If the dataset is in a standard TXT format (flat file), we may use the `read_table` function from Pandas.

In [49]:
txt_data = pd.read_table('data/somedata.txt', sep = "\s+", header = None)
txt_data.head(50)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,12.6,12.3,1.0708,23,154.25,67.75,23.7,134.9,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,2,6.9,6.1,1.0853,22,173.25,72.25,23.4,161.3,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,3,24.6,25.3,1.0414,22,154.00,66.25,24.7,116.0,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,4,10.9,10.4,1.0751,26,184.75,72.25,24.9,164.7,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,5,27.8,28.7,1.0340,24,184.25,71.25,25.6,133.1,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7
5,6,20.6,20.9,1.0502,24,210.25,74.75,26.5,167.0,39.0,104.5,94.4,107.8,66.0,42.0,25.6,35.7,30.6,18.8
6,7,19.0,19.2,1.0549,26,181.00,69.75,26.2,146.6,36.4,105.1,90.7,100.3,58.4,38.3,22.9,31.9,27.8,17.7
7,8,12.8,12.4,1.0704,25,176.00,72.50,23.6,153.6,37.8,99.6,88.5,97.1,60.0,39.4,23.2,30.5,29.0,18.8
8,9,5.1,4.1,1.0900,25,191.00,74.00,24.6,181.3,38.1,100.9,82.5,99.9,62.9,38.3,23.8,35.9,31.1,18.2
9,10,12.0,11.7,1.0722,23,198.25,73.50,25.8,174.4,42.1,99.6,88.6,104.1,63.1,41.7,25.0,35.6,30.0,19.2
10,11,7.5,7.1,1.0830,26,186.25,74.50,23.6,172.3,38.5,101.5,83.6,98.2,59.7,39.7,25.2,32.8,29.4,18.5
11,12,8.5,7.8,1.0812,27,216.00,76.00,26.3,197.7,39.4,103.6,90.9,107.7,66.2,39.2,25.9,37.2,30.2,19.0
12,13,20.5,20.8,1.0513,32,180.50,69.50,26.3,143.5,38.4,102.0,91.6,103.9,63.4,38.3,21.5,32.5,28.6,17.7
13,14,20.8,21.2,1.0505,30,205.25,71.25,28.5,162.5,39.4,104.1,101.8,108.6,66.0,41.5,23.7,36.9,31.6,18.8
14,15,21.7,22.1,1.0484,35,187.75,69.50,27.4,147.0,40.5,101.3,96.4,100.1,69.0,39.0,23.1,36.1,30.5,18.2
15,16,20.5,20.9,1.0512,35,162.75,66.00,26.3,129.3,36.4,99.1,92.8,99.2,63.1,38.7,21.7,31.1,26.4,16.9
16,17,28.1,29.0,1.0333,34,195.75,71.00,27.3,140.8,38.9,101.9,96.4,105.2,64.8,40.8,23.1,36.2,30.8,17.3
17,18,22.4,22.9,1.0468,32,209.25,71.00,29.2,162.5,42.1,107.6,97.5,107.0,66.9,40.0,24.4,38.2,31.6,19.3
18,19,16.1,16.0,1.0622,28,183.75,67.75,28.2,154.3,38.0,106.8,89.6,102.4,64.2,38.7,22.9,37.2,30.5,18.5
19,20,16.5,16.5,1.0610,33,211.75,73.50,27.6,176.8,40.0,106.2,100.5,109.0,65.8,40.6,24.0,37.1,30.1,18.2
20,21,19.0,19.1,1.0551,28,179.00,68.00,27.3,145.1,39.1,103.3,95.9,104.9,63.5,38.0,22.1,32.5,30.3,18.4
21,22,15.3,15.2,1.0640,28,200.50,69.75,29.1,169.8,41.3,111.4,98.8,104.8,63.4,40.6,24.6,33.0,32.8,19.9
22,23,15.7,15.6,1.0631,31,140.25,68.25,21.2,118.2,33.9,86.0,76.4,94.6,57.4,35.3,22.2,27.9,25.9,16.7
23,24,17.6,17.7,1.0584,32,148.75,70.00,21.4,122.6,35.5,86.7,80.0,93.4,54.9,36.2,22.1,29.8,26.7,17.1
24,25,14.2,14.0,1.0668,28,151.25,67.75,23.2,129.8,34.5,90.2,76.3,95.8,58.4,35.5,22.9,31.1,28.0,17.6
25,26,4.6,3.7,1.0911,27,159.25,71.50,21.9,151.9,35.7,89.6,79.7,96.5,55.0,36.7,22.5,29.9,28.2,17.7
26,27,8.5,7.9,1.0811,34,131.50,67.50,20.3,120.3,36.2,88.6,74.6,85.3,51.7,34.7,21.4,28.7,27.0,16.5
27,28,22.4,22.9,1.0468,31,148.00,67.50,22.9,114.9,38.8,97.4,88.7,94.7,57.5,36.0,21.0,29.2,26.6,17.0
28,29,4.7,3.7,1.0910,27,133.25,64.75,22.4,127.0,36.4,93.5,73.9,88.5,50.1,34.5,21.3,30.5,27.9,17.2
29,30,9.4,8.8,1.0790,29,160.75,69.00,23.8,145.7,36.7,97.4,83.5,98.7,58.9,35.3,22.6,30.1,26.7,17.6
30,31,12.3,11.9,1.0716,32,182.00,73.75,23.6,159.7,38.7,100.5,88.7,99.8,57.5,38.7,33.9,32.5,27.7,18.4
31,32,6.5,5.7,1.0862,29,160.25,71.25,22.2,149.8,37.3,93.5,84.5,100.6,58.5,38.8,21.5,30.1,26.4,17.9
32,33,13.4,11.8,1.0719,27,168.00,71.25,23.3,142.5,38.1,93.0,79.1,94.5,57.3,36.2,24.5,29.0,30.0,18.8
33,34,20.9,21.3,1.0502,41,218.50,71.00,30.5,172.7,39.8,111.7,100.5,108.3,67.1,44.2,25.2,37.5,31.5,18.7
34,35,31.1,32.3,1.0263,41,247.25,73.50,32.2,170.4,42.1,117.0,115.6,116.1,71.2,43.3,26.3,37.3,31.7,19.7
35,36,38.2,40.1,1.0101,49,191.75,65.00,32.0,118.4,38.4,118.5,113.1,113.8,61.9,38.3,21.9,32.0,29.8,17.0
36,37,23.6,24.2,1.0438,40,202.25,70.00,29.1,154.5,38.5,106.5,100.9,106.2,63.5,39.9,22.6,35.1,30.6,19.0
37,38,27.5,28.4,1.0346,50,196.75,68.25,29.7,142.6,42.1,105.6,98.8,104.8,66.0,41.5,24.7,33.2,30.5,19.4
38,39,33.8,35.2,1.0202,46,363.15,72.25,48.9,240.5,51.2,136.2,148.1,147.7,87.3,49.1,29.6,45.0,29.0,21.4
39,40,31.3,32.6,1.0258,50,203.00,67.00,31.8,139.4,40.2,114.8,108.1,102.5,61.3,41.1,24.7,34.1,31.0,18.3
40,41,33.1,34.5,1.0217,45,262.75,68.75,39.1,175.8,43.2,128.3,126.2,125.6,72.5,39.6,26.6,36.4,32.7,21.4
41,42,31.7,32.9,1.0250,44,205.00,29.50,29.9,140.1,36.6,106.0,104.3,115.5,70.6,42.5,23.7,33.6,28.7,17.4
42,43,30.4,31.6,1.0279,48,217.00,70.00,31.2,151.1,37.3,113.3,111.2,114.1,67.7,40.9,25.0,36.7,29.8,18.4
43,44,30.8,32.0,1.0269,41,212.00,71.50,29.2,146.7,41.5,106.6,104.3,106.0,65.0,40.2,23.0,35.8,31.5,18.8
44,45,8.4,7.7,1.0814,39,125.25,68.00,19.1,114.7,31.5,85.1,76.0,88.2,50.0,34.7,21.0,26.1,23.1,16.1
45,46,14.1,13.9,1.0670,43,164.25,73.25,21.3,141.1,35.7,96.6,81.5,97.2,58.4,38.2,23.4,29.7,27.4,18.3
46,47,11.2,10.8,1.0742,40,133.50,67.50,20.6,118.5,33.6,88.2,73.7,88.5,53.3,34.5,22.5,27.9,26.2,17.3
47,48,6.4,5.6,1.0665,39,148.50,71.25,20.6,139.0,34.6,89.8,79.5,92.7,52.7,37.5,21.9,28.8,26.8,17.9
48,49,13.4,13.6,1.0678,45,135.75,68.50,20.4,117.6,32.8,92.3,83.4,90.4,52.0,35.8,20.6,28.8,25.5,16.3
49,50,5.0,4.0,1.0903,47,127.50,66.75,20.2,121.2,34.0,83.4,70.4,87.2,50.6,34.4,21.9,26.8,25.8,16.8

In [39]:
print("Data type : ", type(txt_data))
print("Data dims : ", txt_data.shape)

Data type :  <class 'pandas.core.frame.DataFrame'>
Data dims :  (252, 19)

---

### Import XLS file into a DataFrame

If the dataset is in a Microsoft XLS or XLSX format, we may use the `read_excel` function from Pandas.    
However, to use the `read_excel` function, you will need to install the `xlrd` module using Anaconda.

In [40]:
xls_data = pd.read_excel('data/somedata.xlsx', sheet_name = 'Sheet1', header = None)
xls_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,12.6,12.3,1.0708,23,154.25,67.75,23.7,134.9,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,2,6.9,6.1,1.0853,22,173.25,72.25,23.4,161.3,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
2,3,24.6,25.3,1.0414,22,154.00,66.25,24.7,116.0,34.0,95.8,87.9,99.2,59.6,38.9,24.0,28.8,25.2,16.6
3,4,10.9,10.4,1.0751,26,184.75,72.25,24.9,164.7,37.4,101.8,86.4,101.2,60.1,37.3,22.8,32.4,29.4,18.2
4,5,27.8,28.7,1.0340,24,184.25,71.25,25.6,133.1,34.4,97.3,100.0,101.9,63.2,42.2,24.0,32.2,27.7,17.7

In [51]:
print("Data type : ", type(xls_data[0]))
print("Data dims : ", xls_data.shape)

Data type :  <class 'pandas.core.series.Series'>
Data dims :  (252, 19)

---

### Import JSON file into a DataFrame

If the dataset is in a standard JSON format, we may use the `read_json` function from Pandas.

In [42]:
json_data = pd.read_json('data/somedata.json')
json_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,1,12.6,12.3,1.0708,23,154.25,67.75,23.7,134.9,36.2,93.1,85.2,94.5,59.0,37.3,21.9,32.0,27.4,17.1
1,2,6.9,6.1,1.0853,22,173.25,72.25,23.4,161.3,38.5,93.6,83.0,98.7,58.7,37.3,23.4,30.5,28.9,18.2
10,11,7.5,7.1,1.0830,26,186.25,74.50,23.6,172.3,38.5,101.5,83.6,98.2,59.7,39.7,25.2,32.8,29.4,18.5
100,101,20.8,21.2,1.0506,49,198.50,73.50,25.9,157.2,40.1,106.5,95.0,101.7,59.0,39.4,22.3,32.2,31.0,18.6
101,102,20.1,20.4,1.0524,48,173.75,72.00,23.6,138.9,37.0,99.1,92.0,98.3,59.3,38.4,22.4,27.9,26.2,17.0

In [43]:
print("Data type : ", type(json_data))
print("Data dims : ", json_data.shape)

Data type :  <class 'pandas.core.frame.DataFrame'>
Data dims :  (252, 19)

---

### Import HTML table into a DataFrame

If the dataset is in a table formal within an HTML website, we may use the `read_html` function from Pandas.    
Let's try to get the Cast of Kung-Fu Panda : http://www.imdb.com/title/tt0441773/fullcredits/?ref_=tt_ov_st_sm

In [44]:
html_data = pd.read_html('http://www.imdb.com/title/tt0441773/fullcredits/?ref_=tt_ov_st_sm')

In [45]:
print("Data type : ", type(html_data))
print("HTML tables : ", len(html_data))

Data type :  <class 'list'>
HTML tables :  24

In [48]:
html_data[2].head(20)

      0                      1    2                                  3
0   NaN                    NaN  NaN                                NaN
1   NaN             Jack Black  ...                         Po (voice)
2   NaN         Dustin Hoffman  ...                      Shifu (voice)
3   NaN         Angelina Jolie  ...                    Tigress (voice)
4   NaN            Ian McShane  ...                   Tai Lung (voice)
5   NaN            Jackie Chan  ...                     Monkey (voice)
6   NaN             Seth Rogen  ...                     Mantis (voice)
7   NaN               Lucy Liu  ...                      Viper (voice)
8   NaN            David Cross  ...                      Crane (voice)
9   NaN        Randall Duk Kim  ...                     Oogway (voice)
10  NaN             James Hong  ...                   Mr. Ping (voice)
11  NaN             Dan Fogler  ...                       Zeng (voice)
12  NaN  Michael Clarke Duncan  ...           Commander Vachir (voice)
13  NaN           Wayne Knight  ...                  Gang Boss (voice)
14  NaN              Kyle Gass  ...                    KG Shaw (voice)
15  NaN                JR Reed  ...                    JR Shaw (voice)
16  NaN      Laura Kightlinger  ...                 Awed Ninja (voice)
17  NaN            Tanya Haden  ...              Smitten Bunny (voice)
18  NaN         Stephen Kearin  ...  Gong Pig / Grateful Bunny (voice)
19  NaN           Mark Osborne  ...                 Pig Patron (voice)

In [56]:
html_data[2][html_data[2][2] != None]

,0,1,2,3
0,NaN,NaN,NaN,NaN
1,NaN,Jack Black,...,Po (voice)
2,NaN,Dustin Hoffman,...,Shifu (voice)
3,NaN,Angelina Jolie,...,Tigress (voice)
4,NaN,Ian McShane,...,Tai Lung (voice)
5,NaN,Jackie Chan,...,Monkey (voice)
6,NaN,Seth Rogen,...,Mantis (voice)
7,NaN,Lucy Liu,...,Viper (voice)
8,NaN,David Cross,...,Crane (voice)
9,NaN,Randall Duk Kim,...,Oogway (voice)
10,NaN,James Hong,...,Mr. Ping (voice)
11,NaN,Dan Fogler,...,Zeng (voice)
12,NaN,Michael Clarke Duncan,...,Commander Vachir (voice)
13,NaN,Wayne Knight,...,Gang Boss (voice)
14,NaN,Kyle Gass,...,KG Shaw (voice)
15,NaN,JR Reed,...,JR Shaw (voice)
16,NaN,Laura Kightlinger,...,Awed Ninja (voice)
17,NaN,Tanya Haden,...,Smitten Bunny (voice)
18,NaN,Stephen Kearin,...,Gong Pig / Grateful Bunny (voice)
19,NaN,Mark Osborne,...,Pig Patron (voice)
20,NaN,John Stevenson,...,Rhino Guard (voice)
21,NaN,Jeremy Shipp,...,Blind Gator (voice)
22,NaN,Melissa Cobb,...,Bunny Mom (voice)
23,NaN,Kent Osborne,...,Pig Fan (voice)
24,NaN,Emily Burns,...,Bunny Fan 1 (voice)
25,NaN,Stephanie Harvey,...,Bunny Fan 2 (voice)
26,NaN,Riley Osborne,...,Baby Tai Lung (voice)
27,Rest of cast listed alphabetically:,Rest of cast listed alphabetically:,Rest of cast listed alphabetically:,Rest of cast listed alphabetically:
28,NaN,Ben Key,...,Kanye West (uncredited)
29,NaN,Kresimir Mikic,...,Bogomoljka (uncredited)